//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInfo
    {
        public int Id { get; set; }
        public string GameName { get; set; }
        public string GameImg1 { get; set; }
        public string GameImg2 { get; set; }
        public string Slogan1 { get; set; }
        public string Slogan2 { get; set; }
        public string Introduction { get; set; }
        public string Video { get; set; }
        public string GameIndexUrl { get; set; }
        public string ShowType { get; set; }
    }
}
